/**
 * Local illustration assets (web/public/assets, generated by scripts/assets-pipeline.py from the twelve brand illustrations —
 * white background → transparent, WebP + PNG at 256 and 512). Reference ONLY these local paths: no runtime blob URLs anywhere,
 * no remote CDN, no /fallbacks/ (retired). See web/docs/ASSETS.md for the usage table, sizes and the regeneration command.
 */
export type AssetName =
  | "news-card" | "company-logo" | "financial-empty"
  | "voice-orb-idle" | "voice-orb-listening" | "voice-orb-thinking"
  | "upload-dropzone" | "awaiting-input" | "require-creds" | "browser-action"
  | "synced-badge" | "new-chat";
export type AssetSize = 256 | 512;
export type AssetExt = "webp" | "png";

export const ASSET_SIZES: readonly AssetSize[] = [256, 512] as const;
export const ASSET_EXTS: readonly AssetExt[] = ["webp", "png"] as const;

/** Canonical order — matches scripts/assets-pipeline.py NAMES and public/assets/manifest.json keys. */
export const ASSET_NAMES: readonly AssetName[] = [
  "news-card", "company-logo", "financial-empty", "voice-orb-idle", "voice-orb-listening", "upload-dropzone",
  "awaiting-input", "require-creds", "browser-action", "synced-badge", "new-chat", "voice-orb-thinking",
] as const;

export const asset = (name: AssetName, size: AssetSize = 256, ext: AssetExt = "webp") => `/assets/${name}-${size}.${ext}`;

/** `srcSet` for a 1×/2× `<img>`: 256 for 1×, 512 for 2×. Pair with `src={asset(name)}`. */
export const assetSrcSet = (name: AssetName, ext: AssetExt = "webp") => `${asset(name, 256, ext)} 1x, ${asset(name, 512, ext)} 2x`;

/** Named entry points. Default is 256 WebP; `newChat` is 512 because the empty-thread hero renders large. */
export const ASSET = {
  newsCard: asset("news-card"), companyLogo: asset("company-logo"), financialEmpty: asset("financial-empty"),
  voiceIdle: asset("voice-orb-idle"), voiceListening: asset("voice-orb-listening"), voiceThinking: asset("voice-orb-thinking"),
  dropzone: asset("upload-dropzone"), awaitingInput: asset("awaiting-input"), requireCreds: asset("require-creds"), browserAction: asset("browser-action"),
  syncedBadge: asset("synced-badge"), newChat: asset("new-chat", 512),
} as const;
export type AssetKey = keyof typeof ASSET;

/** Shape of public/assets/manifest.json (written by the pipeline; `bytes` and `transparent_pct` are for docs/tests, not runtime). */
export type AssetManifestEntry = {
  webp256: string; png256: string; webp512: string; png512: string;
  bytes: { webp256: number; png256: number; webp512: number; png512: number };
  transparent_pct: number;
  source_bg_pct?: number;
};
export type AssetManifest = Record<AssetName, AssetManifestEntry>;

/** Content-type a static server must answer for each extension (asserted by e2e/assets.spec.ts). */
export const ASSET_CONTENT_TYPE: Record<AssetExt, string> = { webp: "image/webp", png: "image/png" };

/** True only for paths this module owns. Use it to reject remote/blob URLs where an illustration is expected. */
export const isLocalAssetPath = (src: string) => /^\/assets\/[a-z-]+-(256|512)\.(webp|png)$/.test(src);
