/**
 * Local illustration assets (web/public/assets, generated by scripts/assets-pipeline.py from the twelve brand illustrations —
 * white background → transparent, WebP + PNG at 256 and 512). Reference ONLY these local paths: no runtime blob URLs anywhere.
 */
export type AssetName = "news-card" | "company-logo" | "financial-empty" | "voice-orb-idle" | "voice-orb-listening" | "voice-orb-thinking" | "upload-dropzone" | "awaiting-input" | "require-creds" | "browser-action" | "synced-badge" | "new-chat";
export const asset = (name: AssetName, size: 256 | 512 = 256, ext: "webp" | "png" = "webp") => `/assets/${name}-${size}.${ext}`;
export const ASSET = {
  newsCard: asset("news-card"), companyLogo: asset("company-logo"), financialEmpty: asset("financial-empty"),
  voiceIdle: asset("voice-orb-idle"), voiceListening: asset("voice-orb-listening"), voiceThinking: asset("voice-orb-thinking"),
  dropzone: asset("upload-dropzone"), awaitingInput: asset("awaiting-input"), requireCreds: asset("require-creds"), browserAction: asset("browser-action"),
  syncedBadge: asset("synced-badge"), newChat: asset("new-chat", 512),
} as const;
export const ASSET_NAMES: AssetName[] = ["news-card", "company-logo", "financial-empty", "voice-orb-idle", "voice-orb-listening", "voice-orb-thinking", "upload-dropzone", "awaiting-input", "require-creds", "browser-action", "synced-badge", "new-chat"];
