/**
 * Event → interactivity synergy matrix. Single source of truth for the Agent-rail "Why it's interactive" panel,
 * the /docs/interactive-ui route and the smoothness report. Frame names follow submit-query v1 (SSE name / eventType / statusType).
 */
export type SynergyRow = { frame: string; channel: "message" | "thinking" | "agent" | "heartbeat" | "terminal"; ui: string; when: string; why: string; testid?: string };
export const SYNERGY_MATRIX: SynergyRow[] = [
  { frame: "statusLog · plugin_suggestion.initialized / completed (suggestedPlugins[])", channel: "message", ui: "Favicon chips in the Agent rail ('Plugins in this run') and on tool cards", when: "As soon as the planner picks tools, before any call runs", why: "Users see which tools will act, with logos, instead of a blank spinner", testid: "plugin-chip" },
  { frame: "statusLog · initializing / analyzing (+stepQuery)", channel: "message", ui: "Live phase line with elapsed timer; a new step row with a short label", when: "Immediately on arrival", why: "Keeps the first second honest — the run is alive and what it is doing is named" , testid: "pending-row" },
  { frame: "thinking · planning_thinking / step_thinking / fulfillment_thinking", channel: "thinking", ui: "One collapsible 'Thinking' trace with live tokens (virtualised to the last lines)", when: "Streams while collapsed; expand on click", why: "Reasoning stays one click away — present for trust, hidden from the reading line", testid: "thinking-trace" },
  { frame: "thinking · planning_output → statusLog · plan_created (queryPlan)", channel: "message", ui: "Plan stepper: objective sentence + steps with pending / running / done / failed", when: "The objective is typed as the plan JSON streams; plan_created confirms it", why: "Long runs need a map; the stepper is the only place the whole run is visible at once", testid: "plan-stepper" },
  { frame: "statusLog · summarize_history.initialized / completed", channel: "message", ui: "Checkpoint card between steps: shimmer 'Summarizing step N…' → timestamped agentic summary (collapsible)", when: "Optimistically on step start; filled when the summary completes", why: "Multi-step runs are long — a checkpoint shows progress and what the agent now believes", testid: "step-summary" },
  { frame: "thinking · step_output (plugin calls JSON) → statusLog · agents_retrieved / executing", channel: "message", ui: "Tool-call cards: plugin favicon, real input, pulse while running", when: "Each plugin call appears as its JSON streams, before execution", why: "Shows the exact question each tool was asked — never an empty {} card", testid: "plugin-activity" },
  { frame: "statusLog · execution_completed / execution_failed · plugin_sources", channel: "message", ui: "Card ticks green with 'N sources' or turns red 'failed' with the raw frame", when: "The moment the call returns", why: "Trust requires honest failure — a 'Not enough credits' error is shown in red, never a fake green check and never a substituted plugin", testid: "plugin-activity" },
  { frame: "statusLog · fulfilling + fulfillment deltas (answer)", channel: "message", ui: "Progressive markdown; [n] markers and links become numbered citation chips as they arrive; the Sources rail fills incrementally in reserved space", when: "Per delta, coalesced to one paint per animation frame", why: "Citations are evidence — they belong beside the claim while it is being read, not in a list at the end", testid: "citation-chip" },
  { frame: "message · clarification_request / agent · ondemand_agent.awaiting_input", channel: "agent", ui: "Clarification form with quick-reply chips; stream stays open", when: "Planning is blocked on the user", why: "The agent cannot proceed without an answer; the form is the fastest unblock", testid: "clarification-form" },
  { frame: "agent · ondemand_agent.require_creds", channel: "agent", ui: "Inline secure credential form (fields from the frame, posted server-side, never logged)", when: "A plugin needs a secret it does not have", why: "The run cannot continue without the credential; collecting it in place avoids a dead end", testid: "creds-form" },
  { frame: "agent · ondemand_agent.awaiting_browser_action", channel: "agent", ui: "Approval card with the live-browser link and Done / Cancel", when: "A side-effecting browser step needs consent", why: "Side effects need explicit human approval", testid: "approval-card" },
  { frame: "agent · ondemand_agent.filler_start / filler_end", channel: "agent", ui: "Typing filler in the live line (no text committed)", when: "Between agent turns", why: "Masks model latency without inventing content", testid: "pending-row" },
  { frame: "message · metricsLog (publicMetrics)", channel: "message", ui: "Answer badge: model · reasoningMode · plugins · first-event ms · first-token ms · total ms · tokens", when: "At the end of the run", why: "Performance is part of the answer's provenance", testid: "answer-badge" },
  { frame: "heartbeat", channel: "heartbeat", ui: "Nothing drawn; keeps the elapsed timer honest", when: "Every 3 s upstream", why: "Keep-alive only — never treated as content" },
  { frame: "[DONE] / [ERROR]:", channel: "terminal", ui: "Stop turns back into Send; [ERROR] → red error banner with the raw payload", when: "Terminal frame", why: "A disconnect alone proves nothing; the terminal marker is the only end signal", testid: "chat-error" },
];
