import http from 'node:http';
const f = (o) => `data: ${JSON.stringify(o)}\n\n`;
http.createServer((req, res) => {
  if (req.method === 'OPTIONS') { res.writeHead(204, { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'POST' }); return res.end(); }
  let body = ''; req.on('data', (c) => body += c); req.on('end', () => {
    res.writeHead(200, { 'content-type': 'text/event-stream; charset=utf-8', 'cache-control': 'no-cache, no-transform', 'access-control-allow-origin': '*', 'x-accel-buffering': 'no' });
    const mid = 'm1', tc1 = 't1', tc2 = 't2'; let t = 0; const at = (ms, fn) => { t = ms; setTimeout(fn, ms); };
    const q = (() => { try { const j = JSON.parse(body); const u = [...j.messages].reverse().find(m => m.role === 'user'); return typeof u.content === 'string' ? u.content : Array.isArray(u.content) ? u.content.map(p => p.text || '').join(' ') : 'question'; } catch { return 'question'; } })();
    const creds = /creds/i.test(q), ask = /ask|clarif/i.test(q);
    at(20, () => { res.write(f({ type: 'RUN_STARTED', threadId: 'x', runId: 'r' })); res.write(f({ type: 'CUSTOM', name: 'ondemand.status', value: { phase: 'connecting', elapsedMs: 3, pluginIds: ['plugin-1722260873', 'plugin-1741871229'] } })); });
    at(300, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.session', value: { sessionId: 'mock0001', created: true } })); res.write(f({ type: 'CUSTOM', name: 'ondemand.plugins', value: { phase: 'completed', plugins: [{ id: 'plugin-1722260873', name: 'Perplexity' }, { id: 'plugin-1741871229', name: 'GPT Search' }] } })); });
    at(700, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.plan', value: { objective: "I'll pull the latest news for your five context companies, then compare it with the sentiment feed.", steps: [{ id: '1', title: 'Gathering fresh company news', plugins: ['perplexity'] }, { id: '2', title: 'Verifying funding and valuation claims', plugins: ['gpt search'] }, { id: '3', title: 'Ranking movers against the sentiment run' }] } })); res.write(f({ type: 'CUSTOM', name: 'ondemand.step', value: { phase: 'start', stepId: '1', index: 1, label: 'Gathering fresh company news' } })); });
    at(900, () => { res.write(f({ type: 'TOOL_CALL_START', toolCallId: tc1, toolCallName: 'Perplexity', parentMessageId: mid })); res.write(f({ type: 'TOOL_CALL_ARGS', toolCallId: tc1, delta: JSON.stringify({ plugin: 'Perplexity', pluginId: 'plugin-1722260873', query: 'Apptronik, Fervo Energy, Flutterwave, WRITER, Perplexity AI latest news October 2026' }) })); res.write(f({ type: 'TOOL_CALL_END', toolCallId: tc1 })); });
    for (let i = 0; i < 12; i++) at(1000 + i * 120, () => res.write(f({ type: 'CUSTOM', name: 'ondemand.thinking', value: { kind: 'step', delta: 'Checking the news feed for each context company… ' } })));
    at(2600, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.sources', value: { partial: true, pluginId: 'plugin-1722260873', sources: [{ url: 'https://www.reuters.com/technology/fervo-energy-geothermal-2026', title: 'Fervo Energy raises new round for Cape Station', sourceName: 'reuters.com' }, { url: 'https://techcrunch.com/2026/10/apptronik-apollo', title: 'Apptronik ships Apollo to a third auto plant', sourceName: 'techcrunch.com' }] } })); res.write(f({ type: 'TOOL_CALL_RESULT', messageId: 'tm1', toolCallId: tc1, role: 'tool', content: JSON.stringify({ status: 'ok', plugin: 'Perplexity', pluginId: 'plugin-1722260873', sources: 2, durationMs: 1700 }) })); res.write(f({ type: 'CUSTOM', name: 'ondemand.step', value: { phase: 'done', stepId: '1', index: 1 } })); });
    at(2800, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.step', value: { phase: 'start', stepId: '2', index: 2, label: 'Verifying funding and valuation claims' } })); res.write(f({ type: 'CUSTOM', name: 'ondemand.summary', value: { phase: 'start', index: 1, stepId: '2', optimistic: true } })); });
    at(3000, () => { res.write(f({ type: 'TOOL_CALL_START', toolCallId: tc2, toolCallName: 'GPT Search', parentMessageId: mid })); res.write(f({ type: 'TOOL_CALL_ARGS', toolCallId: tc2, delta: JSON.stringify({ plugin: 'GPT Search', pluginId: 'plugin-1741871229', query: 'Fervo Energy Series E valuation October 2026' }) })); res.write(f({ type: 'TOOL_CALL_END', toolCallId: tc2 })); });
    at(4200, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.summary', value: { phase: 'done', index: 1, stepId: '2', text: 'Step 1 found two fresh items: Fervo closed a new Cape Station round (Reuters, 8 Oct) and Apptronik shipped Apollo to a third plant (TechCrunch, 7 Oct). No new news for Flutterwave, WRITER or Perplexity AI in the window. Proceeding to verify the funding figures.', at: new Date().toISOString() } })); });
    if (ask) at(4600, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.awaiting_input', value: { prompt: 'Should the ranking weight funding news above product news?', options: ['Weight funding higher', 'Weight them equally', 'Product news first'] } })); });
    if (creds) at(4600, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.require_creds', value: { pluginId: 'plugin-1716429542', service: 'US Stock Fundamentals', fields: [{ key: 'api_key', label: 'API key', type: 'password' }] } })); });
    const T0 = (ask || creds) ? 9500 : 5200;
    at(T0, () => { res.write(f({ type: 'TOOL_CALL_RESULT', messageId: 'tm2', toolCallId: tc2, role: 'tool', content: JSON.stringify({ status: 'ok', plugin: 'GPT Search', pluginId: 'plugin-1741871229', sources: 0, durationMs: 2100 }) })); res.write(f({ type: 'CUSTOM', name: 'ondemand.step', value: { phase: 'done', stepId: '2', index: 2 } })); res.write(f({ type: 'CUSTOM', name: 'ondemand.step', value: { phase: 'start', stepId: '3', index: 3, label: 'Ranking movers against the sentiment run' } })); res.write(f({ type: 'TEXT_MESSAGE_START', messageId: mid, role: 'assistant' })); });
    const text = "**Fervo Energy moved most** (+0.60 → +0.80). The driver is the new Cape Station financing reported by [Reuters](https://www.reuters.com/technology/fervo-energy-geothermal-2026) on 8 October, which the feed scored as strongly positive.\n\n**Apptronik** is second (+0.30 → +0.45) on the Apollo deployment covered by [TechCrunch](https://techcrunch.com/2026/10/apptronik-apollo). Flutterwave, WRITER and Perplexity AI did not move: no new items reached the feed since the last run.";
    const words = text.split(/(?<=\s)/); words.forEach((w, i) => at(T0 + 200 + i * 45, () => res.write(f({ type: 'TEXT_MESSAGE_CONTENT', messageId: mid, delta: w }))));
    at(T0 + 200 + words.length * 45 + 200, () => { res.write(f({ type: 'CUSTOM', name: 'ondemand.metrics', value: { publicMetrics: { inputTokens: 1200, outputTokens: 310, totalTokens: 1510, ragTimeSec: 2.1, fulfillmentTimeSec: 3.2, totalTimeSec: 5.6 } } })); res.write(f({ type: 'TEXT_MESSAGE_END', messageId: mid })); res.write(f({ type: 'CUSTOM', name: 'ondemand.status', value: { phase: 'done' } })); res.write(f({ type: 'RUN_FINISHED', threadId: 'x', runId: 'r' })); res.write('data: [DONE]\n\n'); res.end(); });
  });
}).listen(3404, '127.0.0.1', () => console.log('mock sse on 3404'));
