import { config } from "./config.js";

/** OpenAPI 3.1 document for the Portfolio API — also the schema registered as the OnDemand 'Portfolio Plugin'. */
export function buildOpenApi(serverUrl: string) {
  const Company = {
    type: "object",
    required: ["id", "name", "slug", "sector", "region", "status", "b_capital_role", "estimate_confidence", "estimate_rationale"],
    properties: {
      id: { type: "integer" }, name: { type: "string" }, slug: { type: "string" }, sector: { type: "string" }, region: { type: "string" },
      stage: { type: ["string", "null"] }, status: { type: "string", description: "private | public (…) | firm | free-text status (renames, mergers)" },
      website: { type: ["string", "null"], format: "uri" }, linkedin_url: { type: ["string", "null"] }, hq: { type: ["string", "null"] }, employees: { type: ["integer", "null"] },
      logo_url: { type: ["string", "null"] },
      brand_tokens: { type: "object", properties: { primary: { type: ["string", "null"] }, secondary: { type: ["string", "null"] }, background: { type: ["string", "null"] }, text: { type: ["string", "null"] }, fonts: { type: "array", items: { type: "string" } }, evidence_tier: { type: "string", enum: ["Verified", "Observed", "Third-party", "Missing"] } } },
      b_capital_fund: { type: ["string", "null"] }, b_capital_role: { type: "string", enum: ["lead", "co-lead", "participant", "unknown", "firm"] }, b_capital_round: { type: ["string", "null"] },
      estimated_ticket_size_usd: { type: ["number", "null"] }, estimated_ownership_pct: { type: ["number", "null"] },
      estimate_confidence: { type: "string", enum: ["high", "medium", "low"] }, estimate_rationale: { type: "string", description: "Always populated; unknowns are prefixed 'ESTIMATE:'" },
      latest_news: { type: "array", items: { $ref: "#/components/schemas/NewsItem" } }, sentiment: { $ref: "#/components/schemas/Sentiment" },
      sources: { type: "array", items: { type: "string" } }, is_focus: { type: "boolean" }, in_brand_matrix: { type: "boolean" }, updated_at: { type: "string", format: "date-time" },
    },
  };
  const NewsItem = { type: "object", required: ["title"], properties: { id: { type: "string" }, title: { type: "string" }, url: { type: ["string", "null"] }, source: { type: ["string", "null"] }, kind: { type: "string" }, published_at: { type: ["string", "null"] }, summary: { type: ["string", "null"] }, image_url: { type: ["string", "null"] }, sentiment_score: { type: ["number", "null"] } } };
  const Evidence = { type: "object", required: ["url", "quote"], properties: { url: { type: "string" }, quote: { type: "string" }, source: { type: "string" } } };
  const Sentiment = { type: "object", required: ["score", "label", "evidence", "updated_at"], properties: { score: { type: "number", minimum: -1, maximum: 1 }, label: { type: "string", enum: ["very negative", "negative", "neutral", "positive", "very positive"] }, evidence: { type: "array", items: { $ref: "#/components/schemas/Evidence" } }, updated_at: { type: "string", format: "date-time" }, delta: { type: ["number", "null"], description: "score minus the previous recorded score" } } };
  const Rollup = { type: "object", properties: { scope: { type: "string", enum: ["portfolio", "sector", "region"] }, key: { type: "string" }, company_count: { type: "integer" }, avg_score: { type: "number" }, label: { type: "string" }, delta: { type: ["number", "null"] }, top_movers: { type: "array", items: { type: "object", properties: { slug: { type: "string" }, name: { type: "string" }, score: { type: "number" }, delta: { type: "number" } } } }, computed_at: { type: "string", format: "date-time" } } };
  const IngestCompany = { type: "object", required: ["slug"], properties: { slug: { type: "string", description: "Company slug (or name — resolved case-insensitively)" }, name: { type: "string" }, sentiment: { type: "object", properties: { score: { type: "number", minimum: -1, maximum: 1 }, label: { type: "string" }, evidence: { type: "array", items: { $ref: "#/components/schemas/Evidence" } } } }, news: { type: "array", items: { $ref: "#/components/schemas/NewsItem" } }, status: { type: "string" }, employees: { type: "integer" }, stage: { type: "string" }, headcount_signal: { type: "string" }, funding_verification: { type: "string" }, pitchbook_status: { type: "string", enum: ["pending", "ok", "skipped"] } } };
  const IngestRequest = { type: "object", required: ["companies"], properties: { workflow_id: { type: "string" }, workflow_name: { type: "string" }, execution_id: { type: "string" }, model: { type: "string" }, run_at: { type: "string", format: "date-time" }, companies: { type: "array", items: { $ref: "#/components/schemas/IngestCompany" } }, rollups: { type: "object", description: "Optional precomputed roll-ups from the workflow LLM node; the server recomputes authoritative roll-ups regardless." } } };
  const PitchbookInvestor = { type: "object", required: ["name"], properties: { name: { type: "string" }, website: { type: ["string", "null"] }, location: { type: ["string", "null"] }, year_founded: { type: ["integer", "null"] }, status: { type: ["string", "null"] }, type: { type: ["string", "null"] }, aum_musd: { type: ["number", "null"] }, dry_powder_musd: { type: ["number", "null"] }, team_size: { type: ["integer", "null"] }, investment_range: { type: ["string", "null"] }, deal_types: { type: "array", items: { type: "string" } }, industries: { type: "array", items: { type: "string" } }, verticals: { type: "array", items: { type: "string" } }, geographies: { type: "array", items: { type: "string" } }, preferences: { type: "array", items: { type: "string" } } } };
  const Sourced = { type: "object", properties: { value: {}, source_url: { type: ["string", "null"] }, published_date: { type: ["string", "null"] }, fetched_at: { type: "string" }, plugin_id: { type: ["string", "null"] } } };
  const Availability = { type: "string", enum: ["VERIFIED", "NOT_AVAILABLE_FROM_PLUGIN", "FROM_ENRICHMENT"] };
  const PitchbookRecord = { type: "object", required: ["slug", "investors", "provenance", "availability"], properties: { slug: { type: "string" }, overview: { oneOf: [{ $ref: "#/components/schemas/Sourced" }, { type: "null" }] }, last_round: { oneOf: [{ $ref: "#/components/schemas/Sourced" }, { type: "null" }] }, valuation_history: { type: "array", items: { $ref: "#/components/schemas/Sourced" } }, investors: { type: "object", required: ["matched"], properties: { matched: { type: "array", items: { $ref: "#/components/schemas/PitchbookInvestor" } }, brief: { type: "string" }, total_reported: { type: ["integer", "null"] } } }, financials: { oneOf: [{ $ref: "#/components/schemas/Sourced" }, { type: "null" }] }, comparables: { type: "array", items: { $ref: "#/components/schemas/Sourced" } }, provenance: { type: "object", properties: { plugin_id: { type: "string", const: "plugin-1777018662" }, session_id: { type: ["string", "null"] }, fetched_at: { type: "string" }, source: { type: "string", const: "pitchbook-investor-finder" }, note: { type: "string" } } }, availability: { type: "object", properties: { overview: Availability, last_round: Availability, valuation_history: Availability, financials: Availability, comparables: Availability, investors: Availability } } } };
  const Error = { type: "object", required: ["message", "errorCode"], properties: { message: { type: "string" }, errorCode: { type: "string" } } };
  const err = (code: string, d: string) => ({ [code]: { description: d, content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } } });
  const q = (name: string, d: string, schema: any = { type: "string" }) => ({ name, in: "query", required: false, description: d, schema });
  const slugParam = { name: "slug", in: "path", required: true, schema: { type: "string" }, description: "Company slug, e.g. perplexity-ai, apptronik, fervo-energy, flutterwave, writer, b-capital" };
  return {
    openapi: "3.1.0",
    info: { title: "B Capital Portfolio Intelligence API", version: config.version, description: "Read API over 136 B Capital portfolio records (135 portfolio companies + the firm) with brand tokens, flagged ownership estimates, news and OnDemand-workflow-scored sentiment (model predefined-deepseek-flash — DeepSeek Flash v4.1). Write-back is a single POST /ingest protected by X-Ingest-Secret.", contact: { name: "B Capital Portfolio Intelligence" }, license: { name: "Proprietary" } },
    servers: [{ url: serverUrl, description: "Deployed API" }],
    tags: [{ name: "companies" }, { name: "sentiment" }, { name: "search" }, { name: "ingest" }, { name: "pitchbook" }, { name: "meta" }],
    paths: {
      "/health": { get: { operationId: "getHealth", tags: ["meta"], summary: "Liveness + DB record count", responses: { "200": { description: "OK", content: { "application/json": { schema: { type: "object", properties: { status: { type: "string" }, db_record_count: { type: "integer" }, db_record_count_total: { type: "integer" }, timestamp: { type: "string" }, version: { type: "string" } } } } } } } } },
      "/openapi.json": { get: { operationId: "getOpenApi", tags: ["meta"], summary: "This OpenAPI 3.1 document", responses: { "200": { description: "OpenAPI document", content: { "application/json": { schema: { type: "object" } } } } } } },
      "/companies": { get: { operationId: "listCompanies", tags: ["companies"], summary: "List portfolio companies with filters and pagination", parameters: [q("sector", "Exact sector, e.g. Technology | Healthcare | Energy & Resilience | Opportunistic"), q("region", "Exact region, e.g. North America | Asia | Europe | Middle East"), q("status", "Substring match on status (private, public, firm, unicorn, renamed…)"), q("role", "B Capital role", { type: "string", enum: ["lead", "co-lead", "participant", "unknown", "firm"] }), q("focus", "true → only the 5 focus companies", { type: "boolean" }), q("page", "1-based page", { type: "integer", default: 1, minimum: 1 }), q("limit", "Page size (1-200)", { type: "integer", default: 50, minimum: 1, maximum: 200 }), q("sort", "name | sentiment | updated_at | ticket", { type: "string", default: "name" })], responses: { "200": { description: "Paginated companies", content: { "application/json": { schema: { type: "object", properties: { data: { type: "array", items: { $ref: "#/components/schemas/Company" } }, pagination: { type: "object", properties: { page: { type: "integer" }, limit: { type: "integer" }, total: { type: "integer" }, total_pages: { type: "integer" } } } } } } } }, ...err("400", "Invalid filter") } } },
      "/companies/{slug}": { get: { operationId: "getCompany", tags: ["companies"], summary: "One company by slug (full record incl. brand tokens, estimates, news, sentiment)", parameters: [slugParam], responses: { "200": { description: "Company", content: { "application/json": { schema: { type: "object", properties: { data: { $ref: "#/components/schemas/Company" } } } } } }, ...err("404", "Unknown slug") } } },
      "/companies/{slug}/news": { get: { operationId: "getCompanyNews", tags: ["companies"], summary: "News items for a company, newest first", parameters: [slugParam, q("limit", "Max items", { type: "integer", default: 20, maximum: 100 }), q("kind", "news | status_change | social | funding")], responses: { "200": { description: "News list", content: { "application/json": { schema: { type: "object", properties: { data: { type: "array", items: { $ref: "#/components/schemas/NewsItem" } }, company: { type: "string" } } } } } }, ...err("404", "Unknown slug") } } },
      "/companies/{slug}/sentiment": { get: { operationId: "getCompanySentiment", tags: ["sentiment"], summary: "Current sentiment with history and delta vs previous run", parameters: [slugParam, q("limit", "History rows", { type: "integer", default: 30, maximum: 365 })], responses: { "200": { description: "Sentiment", content: { "application/json": { schema: { type: "object", properties: { company: { type: "string" }, current: { $ref: "#/components/schemas/Sentiment" }, delta: { type: ["number", "null"] }, history: { type: "array", items: { type: "object", properties: { score: { type: "number" }, label: { type: "string" }, delta: { type: ["number", "null"] }, model: { type: ["string", "null"] }, recorded_at: { type: "string" }, execution_id: { type: ["string", "null"] } } } } } } } } }, ...err("404", "Unknown slug") } } },
      "/sentiment/portfolio": { get: { operationId: "getPortfolioSentiment", tags: ["sentiment"], summary: "Portfolio + sector + region roll-ups, deltas vs previous computation, top movers", responses: { "200": { description: "Roll-ups", content: { "application/json": { schema: { type: "object", properties: { portfolio: { $ref: "#/components/schemas/Rollup" }, sectors: { type: "array", items: { $ref: "#/components/schemas/Rollup" } }, regions: { type: "array", items: { $ref: "#/components/schemas/Rollup" } }, top_movers: { type: "array", items: { type: "object" } }, focus: { type: "array", items: { type: "object" } }, computed_at: { type: "string" } } } } } } } } },
      "/search": { get: { operationId: "search", tags: ["search"], summary: "Full-text search over company name/sector/status/HQ and news titles/summaries", parameters: [{ ...q("q", "Query text (min 2 chars)"), required: true }, q("limit", "Max hits per type", { type: "integer", default: 20, maximum: 100 })], responses: { "200": { description: "Hits", content: { "application/json": { schema: { type: "object", properties: { q: { type: "string" }, companies: { type: "array", items: { type: "object" } }, news: { type: "array", items: { $ref: "#/components/schemas/NewsItem" } } } } } } }, ...err("400", "Missing q") } } },
      "/ingest": { post: { operationId: "ingest", tags: ["ingest"], summary: "Workflow write-back: upsert news + sentiment, recompute roll-ups and deltas", description: "Called by the OnDemand Flow Builder HTTP step at the end of each daily run. Requires header X-Ingest-Secret. Accepts the strict schema below OR a free-form LLM payload (JSON embedded in text is extracted best-effort; unmatched companies are reported, never silently dropped).", security: [{ ingestSecret: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/IngestRequest" } }, "text/plain": { schema: { type: "string", description: "LLM output containing a JSON object" } } } }, responses: { "200": { description: "Ingest summary", content: { "application/json": { schema: { type: "object", properties: { ingest_run_id: { type: "string" }, companies_touched: { type: "integer" }, news_upserted: { type: "integer" }, sentiment_rows: { type: "integer" }, unmatched: { type: "array", items: { type: "string" } }, rollups_recomputed: { type: "integer" }, status: { type: "string" } } } } } }, ...err("401", "Missing/invalid X-Ingest-Secret"), ...err("400", "Unparseable body") } } },
      "/refresh": { post: { operationId: "refresh", tags: ["ingest"], summary: "Pull live news (with images + published dates) via the OnDemand Chat API / Perplexity plugin", description: "Server-side refresh: for each company creates an OnDemand chat session, streams a Perplexity query, stores every plugin source (title, url, domain, imageUrl) as a news item (og:image backfilled when missing), merges into latest_news and records an ingest_runs row (source 'refresh'). Same auth as /ingest (X-Ingest-Secret, Basic password or ?secret=). Synchronous — typically 60–120 s per batch of 3 companies. Without slugs the `limit` stalest companies (by updated_at) are refreshed.", security: [{ ingestSecret: [] }], requestBody: { required: false, content: { "application/json": { schema: { type: "object", properties: { slugs: { type: "array", items: { type: "string" }, description: "Company slugs to refresh (default: stalest companies)" }, limit: { type: "integer", default: 40, maximum: 200 }, concurrency: { type: "integer", default: 3, maximum: 6 } } } } } }, responses: { "200": { description: "Refresh summary", content: { "application/json": { schema: { type: "object", properties: { ingest_run_id: { type: "string" }, status: { type: "string", enum: ["ok", "partial", "error"] }, companies_touched: { type: "integer" }, news_upserted: { type: "integer" }, with_images: { type: "integer" }, dated: { type: "integer" }, errors: { type: "array", items: { type: "string" } }, companies: { type: "array", items: { type: "object", properties: { slug: { type: "string" }, name: { type: "string" }, items: { type: "integer" }, with_images: { type: "integer" }, dated: { type: "integer" }, ms: { type: "integer" }, error: { type: "string", nullable: true } } } }, items: { type: "array", items: { type: "object", properties: { id: { type: "string" }, company_slug: { type: "string" }, title: { type: "string" }, url: { type: "string" }, source: { type: "string", nullable: true }, published_at: { type: "string", nullable: true }, image_url: { type: "string", nullable: true }, fetched_at: { type: "string" } } } }, started_at: { type: "string" }, finished_at: { type: "string" } } } } } }, ...err("401", "Missing/invalid X-Ingest-Secret"), ...err("503", "ONDEMAND_API_KEY / INGEST_SECRET not configured") } } },
      "/refresh/status": { get: { operationId: "getRefreshStatus", tags: ["ingest"], summary: "Last refresh run + scheduler state (public)", responses: { "200": { description: "Status", content: { "application/json": { schema: { type: "object", properties: { running: { type: "boolean" }, last_run: { type: "object", nullable: true, properties: { id: { type: "string" }, status: { type: "string" }, companies_touched: { type: "integer" }, news_upserted: { type: "integer" }, errors: { type: "array", items: { type: "string" } }, started_at: { type: "string" }, finished_at: { type: "string", nullable: true }, model: { type: "string", nullable: true } } }, scheduler: { type: "object", properties: { enabled: { type: "boolean" }, interval_minutes: { type: "integer", nullable: true }, batch_limit: { type: "integer" }, next_scheduled_at: { type: "string", nullable: true } } }, news_items_total: { type: "integer" }, news_items_with_images: { type: "integer" }, timestamp: { type: "string" } } } } } } } } },
      "/pitchbook": { get: { operationId: "listPitchbook", tags: ["pitchbook"], summary: "PitchBook records on file (investor matches per company) + next weekly run", description: "Source: OnDemand plugin plugin-1777018662 'Pitchbook Investor Finder' (operation searchInvestors, auth NONE — account token server-side). Investor matches are VERIFIED; company overview / last round / valuation history / financials / comparables are NOT_AVAILABLE_FROM_PLUGIN.", responses: { "200": { description: "Summary list", content: { "application/json": { schema: { type: "object", properties: { data: { type: "array", items: { type: "object", properties: { slug: { type: "string" }, fetched_at: { type: "string" }, investors: { type: "integer" } } } }, count: { type: "integer" }, next_run_utc: { type: "string" }, workflow_id: { type: ["string", "null"] }, plugin_id: { type: "string" } } } } } } } } },
      "/pitchbook/{slug}": { get: { operationId: "getPitchbook", tags: ["pitchbook"], summary: "PitchBook record for one company (null when not yet fetched)", parameters: [slugParam], responses: { "200": { description: "Record", content: { "application/json": { schema: { type: "object", properties: { company: { type: "string" }, data: { oneOf: [{ $ref: "#/components/schemas/PitchbookRecord" }, { type: "null" }] }, enriched: { type: "boolean" }, next_run_utc: { type: "string" } } } } } }, ...err("404", "Unknown slug") } } },
      "/pitchbook/ingest": { post: { operationId: "pitchbookIngest", tags: ["pitchbook"], summary: "Write PitchBook records (workflow webhook) or fetch them server-side for a list of slugs", description: "Same auth as /ingest (X-Ingest-Secret, Basic password or ?secret=). Body is EITHER {records:[PitchbookRecord]} — validated (slug must exist, investors.matched[] shape) and upserted — OR {slugs:[…], async?:true, concurrency?:1-2} which runs the investor-finder query per slug (≤20 per call, concurrency 2) and writes rows; async returns 202 with a job to poll at /pitchbook/jobs/{id}.", security: [{ ingestSecret: [] }], requestBody: { required: true, content: { "application/json": { schema: { oneOf: [{ type: "object", required: ["records"], properties: { execution_id: { type: "string" }, records: { type: "array", items: { $ref: "#/components/schemas/PitchbookRecord" } } } }, { type: "object", required: ["slugs"], properties: { slugs: { type: "array", items: { type: "string" }, maxItems: 20 }, async: { type: "boolean" }, concurrency: { type: "integer", maximum: 2 }, dry_run: { type: "boolean" } } }] } } } }, responses: { "200": { description: "Written / fetched", content: { "application/json": { schema: { type: "object", properties: { mode: { type: "string", enum: ["records", "slugs"] }, status: { type: "string" }, written: { type: "integer" }, slugs: { type: "array", items: { type: "string" } }, rejected: { type: "array", items: { type: "object" } }, unmatched: { type: "array", items: { type: "string" } }, results: { type: "array", items: { type: "object" } }, next_run_utc: { type: "string" } } } } } }, "202": { description: "Async job started", content: { "application/json": { schema: { type: "object", properties: { job_id: { type: "string" }, status: { type: "string" }, poll: { type: "string" } } } } } }, ...err("400", "Invalid body"), ...err("401", "Missing/invalid X-Ingest-Secret"), ...err("503", "ONDEMAND_API_KEY not configured") } } },
      "/pitchbook/run": { post: { operationId: "pitchbookRun", tags: ["pitchbook"], summary: "'Run now': execute the weekly OnDemand workflow (PITCHBOOK_WORKFLOW_ID) or fall back to a local async fetch of all companies", security: [{ ingestSecret: [] }], responses: { "200": { description: "Workflow execution started", content: { "application/json": { schema: { type: "object", properties: { mode: { type: "string" }, workflow_id: { type: "string" }, execution_id: { type: "string" }, status: { type: "string" }, next_run_utc: { type: "string" } } } } } }, "202": { description: "Local fallback job started (PITCHBOOK_WORKFLOW_ID unset)", content: { "application/json": { schema: { type: "object", properties: { fallback: { type: "string", const: "local" }, job_id: { type: "string" }, status: { type: "string" }, total: { type: "integer" }, poll: { type: "string" }, next_run_utc: { type: "string" } } } } } }, ...err("401", "Missing/invalid X-Ingest-Secret"), ...err("502", "OnDemand execute call failed"), ...err("503", "ONDEMAND_API_KEY not configured") } } },
    },
    components: { securitySchemes: { ingestSecret: { type: "apiKey", in: "header", name: "X-Ingest-Secret" } }, schemas: { Company, NewsItem, Evidence, Sentiment, Rollup, IngestCompany, IngestRequest, PitchbookInvestor, Sourced, PitchbookRecord, Error } },
  };
}
